# TAT-C Propagation, OrbitPy Access Interface Implementation

Example which uses EOSE-API interfaces between TAT-C (orbit propagation) and OrbitPy (access calculations).

In [1]:
import warnings

import tempfile
import os, shutil
import csv

import geopandas as gpd
import pandas as pd

import json
from datetime import datetime, timedelta, timezone
from astropy.time import Time as AstroPy_Time
from shapely.geometry import box, mapping
from scipy.stats import hmean

from scipy.spatial.transform import Rotation as Scipy_Rotation

from joblib import Parallel, delayed

from tatc.schemas import Instrument as TATC_Instrument, Satellite as TATC_Satellite, TwoLineElements
from tatc.analysis import collect_orbit_track, OrbitCoordinate, OrbitOutput

from orbitpy.util import OrbitState as OrbitPy_OrbitState, Spacecraft as OrbitPy_Spacecraft, SpacecraftBus as OrbitPy_SpacecraftBus
from orbitpy.propagator import J2AnalyticalPropagator as OrbitPy_J2AnalyticalPropagator, SGP4Propagator as OrbitPy_SGP4Propagator
from orbitpy.coveragecalculator import GridCoverage as OrbitPy_GridCoverage, find_access_intervals as OrbitPy_find_access_intervals
from orbitpy.grid import Grid as OrbitPy_Grid

from eose.propagation import (
    PropagationSample,
    PropagationRecord,
    PropagationRequest,
    PropagationResponse,
)

from eose.orbits import GeneralPerturbationsOrbitState, Propagator
from eose.satellites import Satellite, SatelliteBus
from eose.utils import CartesianReferenceFrame, PlanetaryCoordinateReferenceSystem, Quaternion, FixedOrientation
from eose.geometry import Position

from eose.access import (
    AccessSample,
    AccessRecord,
    AccessRequest,
    AccessResponse,
)
from eose.grids import UniformAngularGrid

from instrupy import Instrument as InstruPy_Instrument

from eose.instruments import CircularGeometry, RectangularGeometry, BasicSensor

## Define mission parameters

In [4]:
iss_omm_str = '[{"OBJECT_NAME":"ISS (ZARYA)","OBJECT_ID":"1998-067A","EPOCH":"2024-06-07T09:53:34.728000","MEAN_MOTION":15.50975122,"ECCENTRICITY":0.0005669,"INCLINATION":51.6419,"RA_OF_ASC_NODE":3.7199,"ARG_OF_PERICENTER":284.672,"MEAN_ANOMALY":139.0837,"EPHEMERIS_TYPE":0,"CLASSIFICATION_TYPE":"U","NORAD_CAT_ID":25544,"ELEMENT_SET_NO":999,"REV_AT_EPOCH":45703,"BSTAR":0.00033759,"MEAN_MOTION_DOT":0.00019541,"MEAN_MOTION_DDOT":0}]'
iss_omm = json.loads(iss_omm_str)[0]

basic_sensor = BasicSensor(   id="Atom",
                        mass= 100.5,
                        volume= 0.75,
                        power= 150.0,
                        field_of_view = RectangularGeometry(angle_height=60.0, angle_width=30), #CircularGeometry(diameter=60.0)
                        orientation= list([0, 0.258819, 0, 0.9659258]), # +30 deg roll about x-axis (roll)
                        data_rate= 10.5,
                        bits_per_pixel= 16
                    )

satellites=[
        Satellite(
            id="ISS",
            orbit=GeneralPerturbationsOrbitState.from_omm(iss_omm),
            payloads=[
                basic_sensor
            ],
            satellite_bus=SatelliteBus(id="BlueCanyon XB16", orientation=FixedOrientation.NADIR_GEOCENTRIC)
        )
    ]

targets = UniformAngularGrid(
        delta_latitude=20, delta_longitude=20, region=mapping(box(-180, -50, 180, 50))
    ).as_targets()

mission_start = datetime(2024, 1, 1, tzinfo=timezone.utc)
mission_duration = timedelta(days=1)
propagate_time_step = timedelta(minutes=1)

## Run the TAT-C Propagator

In [5]:
def propagate_tatc(request: PropagationRequest) -> PropagationResponse:
    if request.propagator != Propagator.SGP4:
        raise RuntimeError("TAT-C only supports SGP4 propagator.")
    orbit_tracks = Parallel(-1)(
        delayed(collect_orbit_track)(
            TATC_Satellite(
                name=satellite.id,
                orbit=TwoLineElements(tle=satellite.orbit.to_tle()),
            ),
            TATC_Instrument(name="Instrument"),
            pd.date_range(
                request.start,
                request.start + request.duration,
                freq=request.time_step,
            ),
            coordinates=(
                OrbitCoordinate.ECI
                if request.frame == CartesianReferenceFrame.ICRF
                else OrbitCoordinate.ECEF
            ),
            orbit_output=OrbitOutput.POSITION_VELOCITY,
        )
        for satellite in request.satellites
    )
    return PropagationResponse(
        **request.model_dump(exclude="satellite_records"),
        satellite_records=[
            PropagationRecord(
                satellite_id=satellite.id,
                samples=orbit_tracks[i].apply(
                    lambda r: PropagationSample(
                        time=r.time,
                        frame=request.frame,
                        position=r.geometry.coords[0],
                        velocity=r.velocity.coords[0],
                    ),
                    axis=1,
                ),
            )
            for i, satellite in enumerate(request.satellites)
        ],
    )

propagate_request = PropagationRequest(
    satellites=satellites,
    start=mission_start,
    duration=mission_duration,
    frame=CartesianReferenceFrame.ICRF,
    propagator=Propagator.SGP4,
    time_step=propagate_time_step
)

#display(propagate_request.model_dump_json())

tatc_propagation_response = propagate_tatc(propagate_request)

#display(propagation_response.model_dump_json())

propagation_data = tatc_propagation_response.as_dataframe()

display(propagation_data)

,geometry,satellite_id,time,position,velocity
0,POINT Z (83.10851 48.53978 432820.67293),ISS,2024-01-01 00:00:00+00:00,"[-4499686.1202688, -232613.21550674032, 509165...","[-1677.6634157866658, -7252.659671818871, -180..."
1,POINT Z (88.15274 47.03603 432699.62950),ISS,2024-01-01 00:01:00+00:00,"[-4590028.087700935, -666915.9700864203, 49718...","[-1332.576798616102, -7218.509492576278, -2187..."
2,POINT Z (92.88653 45.30148 432541.96420),ISS,2024-01-01 00:02:00+00:00,"[-4659474.854577173, -1098182.7987153332, 4829...","[-981.4248032269486, -7151.498310442072, -2561..."
3,POINT Z (97.30894 43.36259 432355.86862),ISS,2024-01-01 00:03:00+00:00,"[-4707710.266126298, -1524450.42817976, 466472...","[-625.8040584505688, -7051.930817092407, -2922..."
4,POINT Z (101.43038 41.24458 432150.55101),ISS,2024-01-01 00:04:00+00:00,"[-4734514.636033979, -1943778.3089340637, 4478...","[-267.3323844160795, -6920.2597150227775, -327..."
...,...,...,...,...,...
1436,POINT Z (-146.62156 -50.42085 452107.98625),ISS,2024-01-01 23:56:00+00:00,"[2972775.053320527, -3178103.3234068537, -5248...","[4437.035162719276, 6104.25183656856, -1182.33..."
1437,POINT Z (-140.92203 -51.19414 452335.14649),ISS,2024-01-01 23:57:00+00:00,"[3232088.5905753896, -2804948.794978799, -5307...","[4203.456660244225, 6329.483090231624, -783.85..."
1438,POINT Z (-135.06176 -51.65632 452419.33520),ISS,2024-01-01 23:58:00+00:00,"[3476813.008662723, -2419133.0347507023, -5342...","[3950.9149924626354, 6526.134176716588, -381.8..."
1439,POINT Z (-129.12018 -51.79595 452358.25715),ISS,2024-01-01 23:59:00+00:00,"[3705843.9403711245, -2022397.7957213398, -535...","[3680.5378950486106, 6693.328594122815, 21.888..."
1440,POINT Z (-123.18477 -51.60945 452151.60222),ISS,2024-01-02 00:00:00+00:00,"[3918147.0381851722, -1616533.5831391243, -533...","[3393.53079168735, 6830.3183237244875, 425.550..."

## Run OrbitPy Access Calculator

In this example the access calculations use the orbit-propagation results from TAT-C

In [ ]:
def access_orbitpy(request: AccessRequest) -> AccessResponse:

    # create a temporary directory to hold temporary files
    script_directory = os.path.dirname(os.path.abspath("__file__"))
    temp_dir = os.path.join(script_directory, "temp")
    os.makedirs(temp_dir, exist_ok=True)

    #### Enumerate and convert from EOSE-API satellites to OrbitPy satellite objects. ####
    # (Enumeration generates distinct orbit-instrument pairs for satellites equipped with multiple instruments.)
    OrbitPy_Satellites = []
    for satellite in request.satellites:
        for instru in satellite.payloads:
            if instru.id in request.payload_ids:
                instru_type = instru.type
                if instru_type == "BasicSensor":

                    if instru.field_of_view.type == "CircularGeometry":
                        instupy_fov_geom = {
                            "shape": "CIRCULAR",
                            "diameter": instru.field_of_view.diameter,
                        }
                    elif instru.field_of_view.type == "RectangularGeometry":
                        instupy_fov_geom = {
                            "shape": "RECTANGULAR",
                            "angleHeight": instru.field_of_view.angle_height,
                            "angleWidth": instru.field_of_view.angle_width,
                        }
                    else:
                        raise ValueError(
                            f"Only Circular and Rectangular geometries are supported and not {instru.field_of_view.type}"
                        )

                    # Convert orientation in Quaternion to Euler rotations
                    r = Scipy_Rotation.from_quat(list(instru.orientation))
                    (x, y, z) = r.as_euler(
                        "XYZ", degrees=True
                    )  # Conventions 'XYZ' are for intrinsic rotations (used by OrbitPy), while 'xyz' are for extrinsic rotations.

                    instrupy_sensor = InstruPy_Instrument.from_dict(
                        {
                            "@type": "Basic Sensor",
                            "orientation": {
                                "referenceFrame": "SC_BODY_FIXED",
                                "convention": "REF_FRAME_ALIGNED",
                            },
                            "fieldOfViewGeometry": instupy_fov_geom,
                            "orientation": {
                                "referenceFrame": "NADIR_POINTING",
                                "convention": "XYZ",
                                "xRotation": x,
                                "yRotation": y,
                                "zRotation": z,
                            },
                            "@id": instru.id,
                        }
                    )
                else:
                    raise ValueError(
                        f"{instru_type} instrument type is not supported. Only 'BasicSensor' instrument type is supported."
                    )

                tle = satellite.orbit.to_tle()

                orbit_state = OrbitPy_OrbitState.from_dict(
                    {
                        "tle": {
                            "tle_line0": "Unknown",
                            "tle_line1": tle[0],
                            "tle_line2": tle[1],
                        }
                    }
                )

                if (
                    hasattr(satellite, "satellite_bus") is False
                    or satellite.satellite_bus.orientation
                    == FixedOrientation.NADIR_GEOCENTRIC
                ):
                    orbitpy_sat_bus = OrbitPy_SpacecraftBus.from_dict(
                        {
                            "orientation": {
                                "referenceFrame": "Nadir_pointing",
                                "convention": "REF_FRAME_ALIGNED",
                            }
                        }
                    )
                else:
                    warnings.warn(
                        "OrbitPy only processes spacecraft-bus orientation aligned with the NADIR_GEOCENTRIC frame. To account for off-naidr instrument viewing, please specify the instrument orientation relative to the NADIR_GEOCENTRIC frame.",
                        UserWarning,
                    )

                sat = OrbitPy_Spacecraft(
                    _id=satellite.id,
                    orbitState=orbit_state,
                    spacecraftBus=orbitpy_sat_bus,
                    instrument=[instrupy_sensor],
                )

                OrbitPy_Satellites.append(sat)

    #### Format the Target points into OrbitPy Grid object ####
    lon = []
    lat = []
    target_id = []
    # iterate through the Target points
    for tp in request.targets:
        if tp.crs == PlanetaryCoordinateReferenceSystem.EPSG_4326 or tp.crs is None:
            lon.append(tp.position[0])
            lat.append(tp.position[1])
            target_id.append(tp.id)
        else:
            raise ValueError(
                f"{tp.crs} CRS is not supported by OrbitPy. Only 'EPSG_4326' CRS is supported."
            )

    row_to_target_id = (
        {}
    )  # Dictionary to map row numbers ('GP index' in OrbitPy) to target_id
    orbitpy_custom_grid = None
    with tempfile.NamedTemporaryFile(
        mode="w+t", delete=False, dir=temp_dir
    ) as grid_file:
        writer = csv.writer(grid_file)
        writer.writerow(["lat [deg]", "lon [deg]", "id"])

        for row_num, (lat_val, lon_val, target_id_val) in enumerate(
            zip(lat, lon, target_id)
        ):
            writer.writerow([lat_val, lon_val, target_id_val])
            row_to_target_id[row_num] = target_id_val

    orbitpy_custom_grid = OrbitPy_Grid.from_customgrid_dict(
        {"@type": "customGrid", "covGridFilePath": grid_file.name}
    )

    #### run propagation and coverage with OrbitPy ####
    step_size_s = request.time_step.total_seconds()
    if request.propagator != Propagator.J2:
        propagator = OrbitPy_J2AnalyticalPropagator.from_dict(
            {"@type": "J2 ANALYTICAL PROPAGATOR", "stepSize": step_size_s}
        )
    elif request.propagator != Propagator.SGP4:
        propagator = OrbitPy_SGP4Propagator.from_dict(
            {"@type": "SGP4 PROPAGATOR", "stepSize": step_size_s}
        )
    else:
        raise RuntimeError("OrbitPy only supports J2 and SGP4 propagators.")

    #### Convert request time to Julian Date UT1####
    utc_dt = request.start.astimezone(
        timezone.utc
    )  # Convert to UTC (if not already in UTC)
    astropy_utc_time = AstroPy_Time(
        utc_dt, scale="utc"
    )  # Convert to astropy Time object
    astropy_ut1_time = astropy_utc_time.ut1  # Convert to UT1 scale

    start_date_dict = {"@type": "JULIAN_DATE_UT1", "jd": astropy_ut1_time.jd}
    start_date = OrbitPy_OrbitState.date_from_dict(
        start_date_dict
    )  # assumed that the time scale is UT1.
    duration = request.duration.total_seconds() / 86400.0

    for orbitpy_sat in OrbitPy_Satellites:

        # run propagation with OrbitPy
        with tempfile.NamedTemporaryFile(
            mode="w+t", delete=False, dir=temp_dir
        ) as state_cart_file:  # store satellite states in a temporary file.
            propagator.execute(
                orbitpy_sat, start_date, state_cart_file.name, None, duration
            )

            # run access calculations with OrbitPy
            with tempfile.NamedTemporaryFile(
                mode="w+t", delete=False, dir=temp_dir
            ) as access_fl:
                cov_calc = OrbitPy_GridCoverage(
                    grid=orbitpy_custom_grid,
                    spacecraft=orbitpy_sat,
                    state_cart_file=state_cart_file.name,
                )
                instru_id = orbitpy_sat.get_instrument().get_id()
                cov_calc.execute(
                    instru_id=instru_id,
                    mode_id=None,
                    use_field_of_regard=True,
                    out_file_access=access_fl.name,
                    mid_access_only=False,
                )
                intervals_df = OrbitPy_find_access_intervals(access_fl.name)

                grouped_intervals = intervals_df.groupby("GP index")
                access_records = []  # record of accesses at each target point
                for gp_index, group in grouped_intervals:
                    # Iterate over each record in the group
                    access_sample = []
                    for index, row in group.iterrows():
                        access_start = request.start + timedelta(
                            seconds=row["Start time index"] * step_size_s
                        )
                        access_duration = timedelta(
                            seconds=row["Duration"] * step_size_s
                        )
                        # form access sample
                        access_sample.append(
                            AccessSample(
                                satellite_id=orbitpy_sat._id,
                                instrument_id=instru_id,
                                start=access_start,
                                duration=access_duration,
                            )
                        )
                    # Add access record
                    access_records.append(
                        AccessRecord(
                            target_id=row_to_target_id[gp_index], samples=access_sample
                        )
                    )

    # delete the temporary directory
    shutil.rmtree(temp_dir)

    return AccessResponse(
        **request.model_dump(exclude="target_records"), target_records=access_records
    )

'{"start":"2024-01-01T00:00:00Z","duration":"PT1H","satellites":[{"id":"ISS","orbit":{"object_name":"ISS (ZARYA)","object_id":"1998-067A","epoch":"2024-06-07T09:53:34.728000","mean_motion":15.50975122,"eccentricity":0.0005669,"inclination":51.6419,"ra_of_asc_node":3.7199,"arg_of_pericenter":284.672,"mean_anomaly":139.0837,"ephemeris_type":0,"classification_type":"U","norad_cat_id":25544,"element_set_no":999,"rev_at_epoch":45703,"bstar":0.00033759,"mean_motion_dot":0.00019541,"mean_motion_ddot":0.0},"payloads":[]}],"time_step":"PT1M","propagator":"sgp4","frame":"ICRF"}'

'{"start":"2024-01-01T00:00:00Z","duration":"PT1H","satellites":[{"id":"ISS","orbit":{"object_name":"ISS (ZARYA)","object_id":"1998-067A","epoch":"2024-06-07T09:53:34.728000","mean_motion":15.50975122,"eccentricity":0.0005669,"inclination":51.6419,"ra_of_asc_node":3.7199,"arg_of_pericenter":284.672,"mean_anomaly":139.0837,"ephemeris_type":0,"classification_type":"U","norad_cat_id":25544,"element_set_no":999,"rev_at_epoch":45703,"bstar":0.00033759,"mean_motion_dot":0.00019541,"mean_motion_ddot":0.0},"payloads":[]}],"time_step":"PT1M","propagator":"sgp4","frame":"ICRF","satellite_records":[{"satellite_id":"ISS","samples":[{"time":"2024-01-01T00:00:00Z","position":[-4499686.1202688,-232613.21550674032,5091657.311614182],"velocity":[-1677.6634157866658,-7252.659671818871,-1804.8077999287968]},{"time":"2024-01-01T00:01:00Z","position":[-4590028.087700935,-666915.9700864203,4971828.475405545],"velocity":[-1332.576798616102,-7218.509492576277,-2187.9548996394055]},{"time":"2024-01-01T00:02:00Z","position":[-4659474.854577173,-1098182.798715333,4829301.789743175],"velocity":[-981.4248032269486,-7151.498310442072,-2561.1120354711065]},{"time":"2024-01-01T00:03:00Z","position":[-4707710.266126301,-1524450.4281797595,4664727.924286884],"velocity":[-625.8040584505683,-7051.930817092405,-2922.5776733547577]},{"time":"2024-01-01T00:04:00Z","position":[-4734514.636033979,-1943778.3089340634,4478858.111839717],"velocity":[-267.3323844160795,-6920.2597150227775,-3270.702570836473]},{"time":"2024-01-01T00:05:00Z","position":[-4739765.803263393,-2354257.4489344866,4272540.784905103],"velocity":[92.35841105772057,-6757.084038207287,-3603.897317396216]},{"time":"2024-01-01T00:06:00Z","position":[-4723439.752729724,-2754019.127748536,4046717.765024675],"velocity":[451.62986483811886,-6563.146823572038,-3920.6396860773307]},{"time":"2024-01-01T00:07:00Z","position":[-4685610.792771687,-3141243.4513263768,3802420.0173309366],"velocity":[808.844293869678,-6339.332120422664,-4219.481759493104]},{"time":"2024-01-01T00:08:00Z","position":[-4626451.284063706,-3514167.707364251,3540762.984994099],"velocity":[1162.372303991752,-6086.661327825185,-4499.056790313169]},{"time":"2024-01-01T00:09:00Z","position":[-4546230.916459875,-3871094.4808461396,3262941.520609334],"velocity":[1510.6003386121558,-5806.2888538476,-4758.085753739627]},{"time":"2024-01-01T00:10:00Z","position":[-4445315.53251369,-4210399.488523015,2970224.434643201],"velocity":[1851.9382290314395,-5499.497096142408,-4995.38354702006]},{"time":"2024-01-01T00:11:00Z","position":[-4324165.498704787,-4530539.0920629,2663948.6832462465],"velocity":[2184.8267052287624,-5167.690748985457,-5209.864790525812]},{"time":"2024-01-01T00:12:00Z","position":[-4183333.6281379294,-4830057.449404688,2345513.221039017],"velocity":[2507.74482191829,-4812.390449382776,-5400.549184205165]},{"time":"2024-01-01T00:13:00Z","position":[-4023462.6611131923,-5107593.265453644,2016372.5467136714],"velocity":[2819.217252642881,-4435.225781948558,-5566.566374575779]},{"time":"2024-01-01T00:14:00Z","position":[-3845282.3131324467,-5361886.104067294,1678029.9725689348],"velocity":[3117.821402136716,-4037.927670941355,-5707.160289017729]},{"time":"2024-01-01T00:15:00Z","position":[-3649605.9026145535,-5591782.22593945,1332030.650848086],"velocity":[3402.1942869936734,-3622.320195188087,-5821.692897766143]},{"time":"2024-01-01T00:16:00Z","position":[-3437326.57392919,-5796239.918782331,979954.3926924518],"velocity":[3671.0391340380684,-3190.311870410054,-5909.647367854106]},{"time":"2024-01-01T00:17:00Z","position":[-3209413.134206964,-5974334.289490267,623408.3171153236],"velocity":[3923.1316472948715,-2743.886450678815,-5970.630578780111]},{"time":"2024-01-01T00:18:00Z","position":[-2966905.525129004,-6125261.4913232345,264019.36883200955],"velocity":[4157.325896697561,-2285.09330743352,-6004.374975787728]},{"time":"2024-01-01T00:19:00Z","position":[-2710909.954134088,-6248342.362473748,-96573.25420656243],"velocity":[4372.559784303801,-1816.037451538305,-6010.739743384032]},{"time":"2024-01-01T00:20:00Z","position":[-2442593.7111990163,-6343025.457044958,-456725.72316505486],"velocity":[4567.860048812961,-1338.8692672689865,-5989.711289344718]},{"time":"2024-01-01T00:21:00Z","position":[-2163179.7004734613,-6408889.4531345945,-814797.2084316238],"velocity":[4742.346773250793,-855.774032527992,-5941.40303700414]},{"time":"2024-01-01T00:22:00Z","position":[-1873940.717165009,-6445644.927703782,-1169157.4766590274],"velocity":[4895.237367189825,-368.961300356163,-5866.054531590035]},{"time":"2024-01-01T00:23:00Z","position":[-1576193.5020253677,-6453135.4921725225,-1518194.41384998],"velocity":[5025.850000709184,119.34578158084598,-5764.029873982861]},{"time":"2024-01-01T00:24:00Z","position":[-1271292.6070113545,-6431338.287347871,-1860321.4345994014],"velocity":[5133.606474003332,606.9211374848452,-5635.815502749572]},{"time":"2024-01-01T00:25:00Z","position":[-960624.1059201811,-6380363.840778916,-2193984.739663397],"velocity":[5218.034513594368,1091.5463428718388,-5482.017351925128]},{"time":"2024-01-01T00:26:00Z","position":[-645599.1848650469,-6300455.293891812,-2517670.384987484],"velocity":[5278.769492549019,1571.0210462993962,-5303.357418296916]},{"time":"2024-01-01T00:27:00Z","position":[-327647.6468211846,-6191987.010370194,-2829911.128181948],"velocity":[5315.555578950177,2043.1731684688414,-5100.669776928383]},{"time":"2024-01-01T00:28:00Z","position":[-8211.364053448237,-6055462.580845374,-3129293.020785127],"velocity":[5328.246322893032,2505.8688195996297,-4874.896087657867]},{"time":"2024-01-01T00:29:00Z","position":[311262.28798829217,-5891512.242518015,-3414461.716748319],"velocity":[5316.804697767533,2957.021881889251,-4627.080638648574]},{"time":"2024-01-01T00:30:00Z","position":[629326.983530524,-5700889.735074081,-3684128.471110496],"velocity":[5281.302616541945,3394.6032123452246,-4358.364974441682]},{"time":"2024-01-01T00:31:00Z","position":[944543.9553163951,-5484468.616784363,-3937075.8052915363],"velocity":[5221.919947604429,3816.6494284516616,-4069.9821567447684]},{"time":"2024-01-01T00:32:00Z","position":[1255488.4300347692,-5243238.066851368,-4172162.8182072984],"velocity":[5138.943057824875,4221.2712467818665,-3763.2507058352726]},{"time":"2024-01-01T00:33:00Z","position":[1560755.963225732,-4978298.201261242,-4388330.125673142],"velocity":[5032.762912439198,4606.661353117275,-3439.568268368435]},{"time":"2024-01-01T00:34:00Z","position":[1858968.6476614827,-4690854.930930212,-4584604.412693715],"velocity":[4903.87276249511,4971.10178897231,-3100.405055410722]},{"time":"2024-01-01T00:35:00Z","position":[2148781.171558493,-4382214.39129961,-4760102.586177781],"velocity":[4752.8654505763725,5312.9708467556,-2747.2970907199942]},{"time":"2024-01-01T00:36:00Z","position":[2428886.7046439503,-4053776.972869245,-4914035.517780609],"velocity":[4580.430364645115,5630.749471353516,-2381.839305365544]},{"time":"2024-01-01T00:37:00Z","position":[2698022.5916599776,-3707030.982360183,-5045711.3685065545],"velocity":[4387.350068250356,5923.027170463233,-2005.6785106078075]},{"time":"2024-01-01T00:38:00Z","position":[2954975.8346800865,-3343545.9637899487,-5154538.488626464],"velocity":[4174.496632944905,6188.507439840459,-1620.5062761206493]},{"time":"2024-01-01T00:39:00Z","position":[3198588.3470958187,-2964965.7082480863,-5240027.887943231],"velocity":[3942.827695778678,6426.01271202378,-1228.0517359555304]},{"time":"2024-01-01T00:40:00Z","position":[3427761.9633021066,-2573000.9807264274,-5301795.272607568],"velocity":[3693.382261514136,6634.488838121082,-830.0743403303505]},{"time":"2024-01-01T00:41:00Z","position":[3641463.189233569,-2169421.9917344325,-5339562.645679064],"velocity":[3427.2762656957857,6813.009112227339,-428.356567246947]},{"time":"2024-01-01T00:42:00Z","position":[3838727.6797478977,-1756050.6409326175,-5353159.469363508],"velocity":[3145.6979112445174,6960.77784680317,-24.696604535336533]},{"time":"2024-01-01T00:43:00Z","position":[4018664.4295492885,-1334752.5595404713,-5342523.387422516],"velocity":[2849.902787900603,7077.133505136486,379.0989898219833]},{"time":"2024-01-01T00:44:00Z","position":[4180459.664850172,-907428.9779113276,-5307700.506650555],"velocity":[2541.208780811251,7161.551393912529,781.2226431624937]},{"time":"2024-01-01T00:45:00Z","position":[4323380.423197594,-476008.44476726785,-5248845.23662858],"velocity":[2220.9907722070293,7213.645915084349,1179.8731342130934]},{"time":"2024-01-01T00:46:00Z","position":[4446777.80910328,-42438.424773362865,-5166219.687303954],"velocity":[1890.6751383369535,7233.17237207835,1573.262964467121]},{"time":"2024-01-01T00:47:00Z","position":[4550089.9133202685,391323.1987701895,-5060192.624232644],"velocity":[1551.7340425336483,7220.028321008779,1959.6257287911908]},{"time":"2024-01-01T00:48:00Z","position":[4632844.383489459,823316.6881045764,-4931237.981823938],"velocity":[1205.679525485961,7174.254453173334,2337.2234766478414]},{"time":"2024-01-01T00:49:00Z","position":[4694660.63414623,1251589.0537690523,-4779932.935388761],"velocity":[854.0573939709694,7096.034991125746,2704.3540530121877]},{"time":"2024-01-01T00:50:00Z","position":[4735251.684028041,1674202.6657729226,-4606955.533721563],"velocity":[498.44091143179077,6985.697577151286,3059.3584037645774]},{"time":"2024-01-01T00:51:00Z","position":[4754425.609021474,2089243.8421466928,-4413081.894884846],"velocity":[140.4242958706943,6843.712630335564,3400.6278265094497]},{"time":"2024-01-01T00:52:00Z","position":[4752086.599467104,2494831.3822856857,-4199182.969134568],"velocity":[-218.38396617187462,6670.69214667546,3726.611143023614]},{"time":"2024-01-01T00:53:00Z","position":[4728235.611155772,2889125.010902935,-3966220.874507186],"velocity":[-576.3679767954269,6467.387916119902,4035.8217645891405]},{"time":"2024-01-01T00:54:00Z","position":[4682970.60027637,3270333.696593223,-3715244.8126373226],"velocity":[-931.9114375321071,6234.689131296748,4326.844616368546]},{"time":"2024-01-01T00:55:00Z","position":[4616486.333763572,3636723.808055973,-3447386.574298978],"velocity":[-1283.404791714851,5973.619364539827,4598.342882713924]},{"time":"2024-01-01T00:56:00Z","position":[4529073.767911281,3986627.0695678387,-3163855.6465904824],"velocity":[-1629.2524710910448,5685.3328931624,4849.064530926895]},{"time":"2024-01-01T00:57:00Z","position":[4421118.990028289,4318448.275739423,-2865933.936754197],"velocity":[-1967.880213649685,5371.110358027979,5077.848567037054]},{"time":"2024-01-01T00:58:00Z","position":[4293101.719886929,4630672.72570865,-2554970.129875348],"velocity":[-2297.742415388213,5032.3537458145065,5283.630975066412]},{"time":"2024-01-01T00:59:00Z","position":[4145593.370171102,4921873.335961587,-2232373.7010734384],"velocity":[-2617.3294734951587,4670.580692719185,5465.450289025388]},{"time":"2024-01-01T01:00:00Z","position":[3979254.66788142,5190717.391091165,-1899608.6059468514],"velocity":[-2925.1750742780123,4287.418115393767,5622.452746306038]}]}]}'

                                      geometry  ...                                           velocity
0     POINT Z (83.10851 48.53978 432820.67293)  ...  [-1677.6634157866658, -7252.659671818871, -180...
1     POINT Z (88.15274 47.03603 432699.62950)  ...  [-1332.576798616102, -7218.509492576277, -2187...
2     POINT Z (92.88653 45.30148 432541.96420)  ...  [-981.4248032269486, -7151.498310442072, -2561...
3     POINT Z (97.30894 43.36259 432355.86862)  ...  [-625.8040584505683, -7051.930817092405, -2922...
4    POINT Z (101.43038 41.24458 432150.55101)  ...  [-267.3323844160795, -6920.2597150227775, -327...
..                                         ...  ...                                                ...
56  POINT Z (-72.57352 -27.71768 439366.32380)  ...  [-1629.2524710910448, 5685.3328931624, 4849.06...
57  POINT Z (-69.84962 -24.91917 438039.85643)  ...  [-1967.880213649685, 5371.110358027979, 5077.8...
58  POINT Z (-67.25735 -22.06222 436740.62396)  ...  [-2297.742415388213, 5032.3537458145065, 5283....
59  POINT Z (-64.77708 -19.15611 435483.56620)  ...  [-2617.3294734951587, 4670.580692719185, 5465....
60  POINT Z (-62.39060 -16.20918 434282.70383)  ...  [-2925.1750742780123, 4287.418115393767, 5622....

[61 rows x 5 columns]

In [ ]:
request = AccessRequest(
    satellites=satellites,
    targets=targets,
    start=mission_start,
    duration=mission_duration,
    propagation_records=tatc_propagation_response.records,
    payload_ids=["Atom"]
)

display(request.model_dump_json())

access_response = access_orbitpy(request)

#display(access_response.model_dump_json())

access_data = access_response.as_dataframe()

#display(access_data)